name: Gradle and Maven Publish Artifact
description: Publishes a Gradle artifact to a Maven repository
inputs:
  version:
    required: false
    description: "Override the version of the artifact to publish, exported as an environment variable called VERSION and temporarily updates the gradle.properties version property"
  publish_command:
    default: "./gradlew"
    description: "The named Gradle task to run for publishing the artifact"
  publish_task_name:
    default: "publish"
    description: "The named Gradle task to run for publishing the artifact"
  build_file:
    default: ""
    description: "If you want to use a build file, specify the command and the file name. E.g., '--build-file library.gradle'"
  publish_command_options:
    default: "--info"
    description: "If you want to use any options for the publish command, specify them here. E.g., '--info'"
  snapshot:
    required: false
    default: "false"
    description: "Whether the version is a snapshot version or not. if gradle, a gradle.properties file is expected and the version is specified without a -snapshot suffix"
    
runs:
    using: "composite"
    steps:
      - if: ${{ inputs.version }}
        name: Set Version
        shell: bash
        env:
          version: ${{ inputs.version }}
        run: |
          echo "VERSION=${version}" >> $GITHUB_ENV
          if [ -f gradle.properties ]; then
            sed -i.bak "/^version/s/=.*/=${version}/" gradle.properties
          fi
      - if: ${{ inputs.snapshot != 'false' }}
        name: Add Snapshot to version-tag
        shell: bash
        run: |
          if [ -f gradle.properties ]; then
            sed -i.bak '/^version/s/$/-SNAPSHOT/' gradle.properties
          fi
      - name: Gradle Publish
        shell: bash
        env:
          publish_task_name: ${{ inputs.publish_task_name }}
          build_file: ${{ inputs.build_file }}
          publish_command_options: ${{ inputs.publish_command_options }}
        run: ./gradlew ${publish_task_name} ${build_file} ${publish_command_options}