  name: Update Artifact Version
  description: Update artifact version files and (enabled by default) pushes the changes back to the repo
  inputs:
    version:
      description: "The next (semver) version of the artifact"
      required: true
    version_file_name:
      description: "The name of the file containing the version number to update"
      required: true
    version_file_variable_name:
      description: "The name of the file variable containing the version number to update"
      required: false
      default: "version"
    push_to_repo:
      description: "Whether to push the new version back to the repo"
      required: false
      default: "true"
  
  outputs:
    version:
      value: ${{ steps.result.outputs.version }}
      description: "The updated version of the artifact"
      
  runs:
    using: "composite"
    steps:
      - name: Insert New Version Into File
        id: result
        shell: bash
        env:
          GHA_MAVENCENTRAL_VERSION: ${{ inputs.version }}
          GHA_MAVENCENTRAL_VERSION_FILE_NAME: ${{ inputs.version_file_name }}
          GHA_MAVENCENTRAL_VERSION_FILE_VARIABLE_NAME: ${{ inputs.version_file_variable_name }}
        run: |
          file_ext=$(echo "$GHA_MAVENCENTRAL_VERSION_FILE_NAME" | awk -F. '{print tolower($NF)}')
          if [ "$file_ext" = "properties" ]; then
            sed -i "s/${GHA_MAVENCENTRAL_VERSION_FILE_VARIABLE_NAME}=.*/${GHA_MAVENCENTRAL_VERSION_FILE_VARIABLE_NAME}=$GHA_MAVENCENTRAL_VERSION/" ${GHA_MAVENCENTRAL_VERSION_FILE_NAME}
          elif [ "$file_ext" = "xml" ]; then
            mvn versions:set -f $GHA_MAVENCENTRAL_VERSION_FILE_NAME -DnewVersion=$GHA_MAVENCENTRAL_VERSION -DgenerateBackupPoms=false -DprocessAllModules=true
          else
            echo "Expected a version file to be a gradle .properties or pom .xml file for version replacement"
            exit 1
          fi

          echo "Inserted new version $GHA_MAVENCENTRAL_VERSION into file $GHA_MAVENCENTRAL_VERSION_FILE_NAME"
          echo "VERSION=$GHA_MAVENCENTRAL_VERSION" >> $GITHUB_ENV
          echo "version=$GHA_MAVENCENTRAL_VERSION" >> $GITHUB_OUTPUT

      - name: Push Version
        if: ${{ inputs.push_to_repo == 'true' }}
        shell: bash
        env:
            GHA_MAVENCENTRAL_GITHUB_REF_NAME: ${{ github.ref }}
            GHA_MAVENCENTRAL_VERSION: ${{ steps.results.outputs.version }}
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add "**/pom.xml" "**/gradle.properties"
          git commit -m "chore(bump): Bump version to ${GHA_MAVENCENTRAL_VERSION} [skip ci]"
          git push origin "${GHA_MAVENCENTRAL_GITHUB_REF_NAME}"