name: Increment Artifact Version
description: Increment artifact version files
inputs:
  version_previous:
    description: "The previous (semver) version of the artifact"
    required: true
  version_next:
    description: "The next (semver) version of the artifact. Increments can be noop (''), automatically detected ('auto') from the commit message, partially incremented using ('major', 'minor', 'patch'), or be forcefully defined (e.g. '1.3.0')"
    required: false
    default: "auto" #  noop (''), auto, major, minor, patch or a semver version
  version_next_suffix:
    description: "The next version of the artifact's suffix. Usual values would be -snapshot or -prerelease"
    required: false
    default: ""

outputs:
  version:
    value: ${{ steps.result.outputs.version }}
    description: "The new version of the artifact"

runs:
  using: "composite"
  steps:
    - name: Increment Version
      id: result
      shell: bash
      env:
        GHA_MAVENCENTRAL_VERSION_PREVIOUS: ${{ inputs.version_previous }}
        GHA_MAVENCENTRAL_VERSION_NEXT: ${{ inputs.version_next }}
        GHA_MAVENCENTRAL_VERSION_NEXT_SUFFIX: ${{ inputs.version_next_suffix }}
      run: |
        # If next version is not defined, automatically increment the patch version,
        # or if defined, the commit message
        if [ "$GHA_MAVENCENTRAL_VERSION_NEXT" != "" ]; then
          if [ "$GHA_MAVENCENTRAL_VERSION_NEXT" = "auto" ]; then
            version_increment="patch"
            commit_message=$(git log --format="%B" -n 1)
            
            if [[ $commit_message =~ \[ ]]; then
              bracket_payloads=$(echo "$commit_message" | grep -Po "(?<=\[)[^\]]*(?=\])")
              
              while IFS= read -r BRACKET_PAYLOAD; do
                bracket_payload_trimmed=$(echo "$BRACKET_PAYLOAD" | tr -d '[:blank:]')
                bracket_payload_trimmed_lowercase=$(tr '[:upper:]' '[:lower:]' <<<"$bracket_payload_trimmed" )
                
                # detect type      
                if [ "$bracket_payload_trimmed_lowercase" = "minor" ]; then
                  version_increment="minor"
                elif [ "$bracket_payload_trimmed_lowercase" = "major" ]; then
                  version_increment="major"
                elif [ "$bracket_payload_trimmed_lowercase" = "patch" ]; then
                  version_increment="patch"
                fi

              done <<< "$bracket_payloads"
            fi
          else
            version_increment=$(echo $GHA_MAVENCENTRAL_VERSION_NEXT | xargs)
          fi

          major="$(echo "$GHA_MAVENCENTRAL_VERSION_PREVIOUS" | cut -d. -f1)"
          major=${major:-0}
          minor=$(echo "$GHA_MAVENCENTRAL_VERSION_PREVIOUS" | cut -d. -f2)
          minor=${minor:-0}
          patch=$(echo "$GHA_MAVENCENTRAL_VERSION_PREVIOUS" | cut -d. -f3)
          patch=${patch:-0}

          if [ "$version_increment" = "minor" ]; then
            minor="$((minor + 1))"
            patch="0"
          elif [ "$version_increment" = "major" ]; then
            major="$((major + 1))"
            minor="0"
            patch="0"
          elif [ "$version_increment" = "patch" ]; then
            patch="$((patch + 1))"
          else 
            semver_regex='^v?(0|[0-9]*)\.(0|[0-9]*)\.(0|[0-9]*$)'
            if [[ "$version_increment" =~ $semver_regex ]]; then
              major=${BASH_REMATCH[1]}
              minor=${BASH_REMATCH[2]}
              patch=${BASH_REMATCH[3]}
            else
              echo "Expected increment to be 'patch', 'minor', 'major' or a static version e.g. '1.0.0', got $version_increment"
              exit 1
            fi
          fi

          new_version="$major.$minor.$patch$GHA_MAVENCENTRAL_VERSION_NEXT_SUFFIX"
        else
          new_version="$GHA_MAVENCENTRAL_VERSION_PREVIOUS"
        fi
        
        echo "Next version is $new_version"
        echo "VERSION=$new_version" >> $GITHUB_ENV
        echo "version=$new_version" >> $GITHUB_OUTPUT