name: Entur/Maven-Central/CI

on:
  pull_request:

jobs:
  test-get-version:
      runs-on: ubuntu-24.04
      steps:
        - uses: actions/checkout@v4
          with:
            persist-credentials: false

        - id: get-version-gradle-good
          uses: ./.github/actions/get-version
          with:
            version_strategy: "file"
            version_file_name: "fixture/gradle.good.properties"

        - name: Test Good gradle.properties file
          shell: bash
          env: 
            GHA_MAVENCENTRAL_TEST_VERSION: ${{ steps.get-version-gradle-good.outputs.version }}
          run: |
            if [[ "$GHA_MAVENCENTRAL_TEST_VERSION" != "1.0.0" ]]; then
                echo "Previous version $GHA_MAVENCENTRAL_TEST_VERSION not equal to 1.0.0"
                exit 1
            fi

        - id: get-version-gradle-good-alt
          uses: ./.github/actions/get-version
          with:
            version_strategy: "file"
            version_file_name: "fixture/gradle.good.properties"
            version_variable_name: "alt_version"

        - name: Test Good gradle.properties with different version variable name
          shell: bash
          env: 
            GHA_MAVENCENTRAL_TEST_VERSION: ${{ steps.get-version-gradle-good-alt.outputs.version }}
          run: |
            if [[ "$GHA_MAVENCENTRAL_TEST_VERSION" != "1.2.4" ]]; then
                echo "Previous version $GHA_MAVENCENTRAL_TEST_VERSION not equal to 1.2.4"
                exit 1
            fi

        - id: get-version-maven-good
          uses: ./.github/actions/get-version
          with:
            version_strategy: "file"
            version_file_name: "fixture/pom.good.xml"

        - name: Test Good pom.xml file
          shell: bash
          env: 
            GHA_MAVENCENTRAL_TEST_VERSION: ${{ steps.get-version-maven-good.outputs.version }}
          run: |
            if [[ "$GHA_MAVENCENTRAL_TEST_VERSION" != "1.50.3" ]]; then
                echo "Previous version $GHA_MAVENCENTRAL_TEST_VERSION not equal to 1.50.3"
                exit 1
            fi

        - id: get-version-maven-good-alt
          uses: ./.github/actions/get-version
          with:
            version_strategy: "file"
            version_file_name: "fixture/pom.good.xml"
            version_variable_name: "modelVersion"

        - name: Test Good pom.xml with different version variable name
          shell: bash
          env: 
            GHA_MAVENCENTRAL_TEST_VERSION: ${{ steps.get-version-maven-good-alt.outputs.version }}
          run: |
            if [[ "$GHA_MAVENCENTRAL_TEST_VERSION" != "4.0.0" ]]; then
                echo "Previous version $GHA_MAVENCENTRAL_TEST_VERSION not equal to 4.0.0"
                exit 1
            fi

        # TODO:
        # We need to add tests for tag based version fetching

  test-update-version:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - id: get-version-gradle-good
        uses: ./.github/actions/get-version
        with:
          version_strategy: "file"
          version_file_name: "fixture/gradle.good.properties"

      - id: update-version-auto-gradle-good
        uses: ./.github/actions/update-version
        with:
          version_file_name: "fixture/gradle.good.properties"
          previous_version: ${{ steps.get-version-gradle-good.outputs.version }}
          push_to_repo: false

      - id: get-version-auto-gradle-good
        uses: ./.github/actions/get-version
        with:
          version_strategy: "file"
          version_file_name: "fixture/gradle.good.properties"

      - name: Test gradle.properties version auto update
        shell: bash
        env: 
          GHA_MAVENCENTRAL_TEST_VERSION: ${{ steps.get-version-auto-gradle-good.outputs.version }}
        run: |
          if [[ "$GHA_MAVENCENTRAL_TEST_VERSION" != "1.0.1" ]]; then
              echo "Previous version $GHA_MAVENCENTRAL_TEST_VERSION not equal to 1.0.1"
              exit 1
          fi
    
      - id: update-version-increment-gradle-good
        uses: ./.github/actions/update-version
        with:
          version_file_name: "fixture/gradle.good.properties"
          previous_version: ${{ steps.update-version-auto-gradle-good.outputs.version }}
          next_version: "minor"
          push_to_repo: false

      - id: get-version-increment-gradle-good
        uses: ./.github/actions/get-version
        with:
          version_strategy: "file"
          version_file_name: "fixture/gradle.good.properties"

      - name: Test gradle.properties version increment update
        shell: bash
        env: 
          GHA_MAVENCENTRAL_TEST_VERSION: ${{ steps.get-version-increment-gradle-good.outputs.version }}
        run: |
          if [[ "$GHA_MAVENCENTRAL_TEST_VERSION" != "1.1.0" ]]; then
              echo "Previous version $GHA_MAVENCENTRAL_TEST_VERSION not equal to 1.1.0"
              exit 1
          fi

      - id: update-version-static-gradle-good
        uses: ./.github/actions/update-version
        with:
          version_file_name: "fixture/gradle.good.properties"
          previous_version: ${{ steps.update-version-increment-gradle-good.outputs.version }}
          next_version: "minor"
          push_to_repo: false

      - id: get-version-static-gradle-good
        uses: ./.github/actions/get-version
        with:
          version_strategy: "file"
          next_version: "2.3.5"
          version_file_name: "fixture/gradle.good.properties"

      - name: Test gradle.properties static version update
        shell: bash
        env: 
          GHA_MAVENCENTRAL_TEST_VERSION: ${{ steps.get-version-static-gradle-good.outputs.version }}
        run: |
          if [[ "$GHA_MAVENCENTRAL_TEST_VERSION" != "2.3.5" ]]; then
              echo "Previous version $GHA_MAVENCENTRAL_TEST_VERSION not equal to 2.3.5"
              exit 1
          fi

  update-gradle-publish-doc:
    needs: [test-get-version, test-update-version]
    uses: entur/gha-meta/.github/workflows/auto-doc.yml@v1.3.0
    with: 
      workflow_file: .github/workflows/gradle-publish.yml
      readme_file: README-gradle-publish.md